Feature/initial setup
sachyshyn/stackoverflow-parody pull request #4
Opened 2024-12-16 17:16 UTC by sachyshyn

- added dockerization;
- added TypeORM;
- added Redis as cache;
- added npm scripts for migrations.

2024-12-17 08:45 UTC, MishaShatilo requested changes

2024-12-17 08:45 UTC, MishaShatilo commented on src/main.ts
>    const app = await NestFactory.create(AppModule);
Давай добавим 

1. Swagger(https://docs.nestjs.com/openapi/introduction)
2. Exception filter(https://docs.nestjs.com/exception-filters)
3. Validation pipe(https://docs.nestjs.com/pipes#global-scoped-pipes)
4. cors + versioning(https://docs.nestjs.com/techniques/versioning, https://docs.nestjs.com/security/cors)

2024-12-17 08:45 UTC, MishaShatilo commented on Dockerfile
Давай сделаем мульти стейдж докер первый стейдж билд второй ранит, плюс копируем лок файл и делаем npm ci

2024-12-19 18:20 UTC, sachyshyn commented on src/main.ts
>    const app = await NestFactory.create(AppModule);
@MishaShatilo обновил, но не добавлял фильтры, я их использую по месту назначения в самих методах/декораторах

2024-12-19 19:28 UTC, sachyshyn commented on Dockerfile
@MishaShatilo добавил

2025-01-07 13:52 UTC, merged